### ISSUE TITLE
CompatHelper

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/EllipticalSliceSampling.jl#4]
Would be nice to have CompatHelper set up here.

**Comment by devmotion** [comment]
I'm a bit surprised - CompatHelper was set up and working before I transferred the repo to TuringLang (see https://github.com/TuringLang/EllipticalSliceSampling.jl/pull/1).

**Comment by devmotion** [comment]
Maybe Github Actions have to be enabled explicitly? 🤔

**Comment by devmotion** [comment]
Should be enabled now.

**Comment by mohamed82008** [comment]
Cool thanks!
